d3.select('body')
  .append('div')
  .property('foo', true)
  .append('div')
  .html('<p><p>')
  .select('p')
  .text('text')
  .append('svg')
  .attr('width', 960)
  .attr('height', 500)
  .classed('foo', true)
  .append('g')
  .style('transform', 'translate(20,20)')
  .append('rect')
  .attr('x', 10);
